---
- name: Apply sysctl parameters.
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
  with_dict: '{{ sysctl_config }}'
  ignore_errors: true
  tags:
    - sysctl
